function cell(type, value) {
  return value === undefined ? { type } : { type, value };
}

function room(label, x, y, spec) {
  const output = {
    label,
    x,
    y,
    type: spec.type
  };

  if (spec.value !== undefined) {
    output.value = spec.value;
  }

  return output;
}

function buildLevel(definition) {
  const idByLabel = new Map();
  const rooms = definition.rooms.map((roomSpec, index) => {
    const roomId = index + 1;
    const roomData = {
      id: roomId,
      x: roomSpec.x,
      y: roomSpec.y,
      type: roomSpec.type
    };

    if (roomSpec.value !== undefined) {
      roomData.value = roomSpec.value;
    }

    idByLabel.set(roomSpec.label, roomId);
    return roomData;
  });

  return {
    id: definition.id,
    name: definition.name,
    shortName: definition.shortName,
    playerPower: definition.playerPower,
    playerStart: idByLabel.get("s"),
    winRoom: idByLabel.get("boss"),
    tip: definition.tip,
    rooms,
    links: definition.links.map(([from, to]) => [idByLabel.get(from), idByLabel.get(to)])
  };
}

function makeLessonLevel(config) {
  return buildLevel({
    id: config.id,
    name: config.name,
    shortName: config.shortName,
    playerPower: config.playerPower,
    tip: config.tip,
    rooms: [
      room("boss", 1, 0, cell("boss", config.boss)),
      room("g", 1, 1, config.g),
      room("d", 0, 2, config.d),
      room("e", 1, 2, config.e),
      room("f", 2, 2, config.f),
      room("a", 0, 3, config.a),
      room("b", 1, 3, config.b),
      room("c", 2, 3, config.c),
      room("s", 1, 4, cell("start"))
    ],
    links: [
      ["s", "a"],
      ["s", "b"],
      ["s", "c"],
      ["a", "d"],
      ["a", "e"],
      ["b", "d"],
      ["b", "e"],
      ["b", "f"],
      ["c", "e"],
      ["c", "f"],
      ["d", "g"],
      ["e", "g"],
      ["f", "g"],
      ["g", "boss"]
    ]
  });
}

function makeTowerLevel(config) {
  return buildLevel({
    id: config.id,
    name: config.name,
    shortName: config.shortName,
    playerPower: config.playerPower,
    tip: config.tip,
    rooms: [
      room("boss", 1.5, 0, cell("boss", config.boss)),
      room("k", 1, 1, config.k),
      room("l", 2, 1, config.l),
      room("h", 0.5, 2, config.h),
      room("i", 1.5, 2, config.i),
      room("j", 2.5, 2, config.j),
      room("d", 0, 3, config.d),
      room("e", 1, 3, config.e),
      room("f", 2, 3, config.f),
      room("g", 3, 3, config.g),
      room("a", 0.5, 4, config.a),
      room("b", 1.5, 4, config.b),
      room("c", 2.5, 4, config.c),
      room("s", 1.5, 5, cell("start"))
    ],
    links: [
      ["s", "a"],
      ["s", "b"],
      ["s", "c"],
      ["a", "d"],
      ["a", "e"],
      ["b", "e"],
      ["b", "f"],
      ["c", "f"],
      ["c", "g"],
      ["d", "h"],
      ["e", "h"],
      ["e", "i"],
      ["f", "i"],
      ["f", "j"],
      ["g", "j"],
      ["h", "k"],
      ["i", "k"],
      ["i", "l"],
      ["j", "l"],
      ["k", "boss"],
      ["l", "boss"]
    ]
  });
}

const E = (value) => cell("enemy", value);
const T = (value) => cell("treasure", value);
const K = (value = 1) => cell("key", value);
const L = (value = 1) => cell("lock", value);
const P = (value) => cell("trap", value);

window.STICK_TOWER_LEVELS = [
  makeLessonLevel({
    id: 1,
    name: "第 1 关 · 晨间热身",
    shortName: "晨间热身",
    playerPower: 10,
    boss: 24,
    tip: "第一批路线先练手，走过的格子不能回头，选顺手的一条就继续爬。",
    a: E(5),
    b: T(4),
    c: E(15),
    d: P(6),
    e: E(8),
    f: T(3),
    g: T(6)
  }),
  makeLessonLevel({
    id: 2,
    name: "第 2 关 · 小赚一手",
    shortName: "小赚一手",
    playerPower: 12,
    boss: 29,
    tip: "别想着回头补收益，选完一格就要一路负责到底。",
    a: E(8),
    b: P(5),
    c: E(18),
    d: E(14),
    e: T(5),
    f: T(4),
    g: E(10)
  }),
  makeLessonLevel({
    id: 3,
    name: "第 3 关 · 钥匙门前",
    shortName: "钥匙门前",
    playerPower: 14,
    boss: 23,
    tip: "先摸钥匙再冲门，少走一步都不行。",
    a: K(),
    b: E(9),
    c: E(20),
    d: T(10),
    e: P(7),
    f: E(16),
    g: L()
  }),
  makeLessonLevel({
    id: 4,
    name: "第 4 关 · 刺尖试算",
    shortName: "刺尖试算",
    playerPower: 16,
    boss: 32,
    tip: "这关开始要算陷阱账，少吃一口补给都可能不够打 Boss。",
    a: E(8),
    b: P(6),
    c: T(7),
    d: E(20),
    e: P(10),
    f: E(9),
    g: E(12)
  }),
  makeLessonLevel({
    id: 5,
    name: "第 5 关 · 双门分流",
    shortName: "双门分流",
    playerPower: 18,
    boss: 24,
    tip: "锁门不吓人，吓人的是拿错钥匙之后已经没法回头。",
    a: T(5),
    b: E(7),
    c: E(21),
    d: P(8),
    e: K(),
    f: E(17),
    g: L()
  }),
  makeLessonLevel({
    id: 6,
    name: "第 6 关 · 宝箱迷眼",
    shortName: "宝箱迷眼",
    playerPower: 20,
    boss: 38,
    tip: "宝箱看着香，但只拿眼前的那口，后面可能就断档了。",
    a: T(5),
    b: E(9),
    c: P(7),
    d: E(8),
    e: E(22),
    f: P(11),
    g: T(10)
  }),
  makeLessonLevel({
    id: 7,
    name: "第 7 关 · 钥匙与代价",
    shortName: "钥匙与代价",
    playerPower: 22,
    boss: 28,
    tip: "钥匙在边路，补给在高位，这关开始像真的爬塔了。",
    a: E(11),
    b: P(9),
    c: K(),
    d: E(26),
    e: P(12),
    f: T(9),
    g: L()
  }),
  makeLessonLevel({
    id: 8,
    name: "第 8 关 · 起步总测",
    shortName: "起步总测",
    playerPower: 24,
    boss: 42,
    tip: "前 8 关的东西都在这里了，起步阶段先在这儿收个尾。",
    a: E(13),
    b: T(8),
    c: E(28),
    d: P(10),
    e: E(10),
    f: T(5),
    g: E(14)
  }),
  makeTowerLevel({
    id: 9,
    name: "第 9 关 · 陷阱坡道",
    shortName: "陷阱坡道",
    playerPower: 26,
    boss: 46,
    tip: "地图变宽了，错一次还不是回头补，而是直接断线。",
    a: E(16),
    b: T(6),
    c: E(30),
    d: P(8),
    e: E(12),
    f: E(22),
    g: T(5),
    h: E(28),
    i: T(9),
    j: E(32),
    k: E(14),
    l: P(18)
  }),
  makeTowerLevel({
    id: 10,
    name: "第 10 关 · 门后补给",
    shortName: "门后补给",
    playerPower: 28,
    boss: 50,
    tip: "先打还是先拿，看起来都能走，实际上只够走一条。",
    a: E(8),
    b: P(7),
    c: E(24),
    d: E(18),
    e: T(7),
    f: T(6),
    g: E(26),
    h: E(13),
    i: P(9),
    j: E(31),
    k: T(10),
    l: E(20)
  }),
  makeTowerLevel({
    id: 11,
    name: "第 11 关 · 窄路围堵",
    shortName: "窄路围堵",
    playerPower: 30,
    boss: 54,
    tip: "边路看似轻松，但中层一旦走错，就会被数值卡死。",
    a: E(17),
    b: E(14),
    c: T(8),
    d: P(10),
    e: E(22),
    f: E(12),
    g: T(5),
    h: E(29),
    i: E(16),
    j: P(12),
    k: E(32),
    l: E(18)
  }),
  makeTowerLevel({
    id: 12,
    name: "第 12 关 · 三岔值守",
    shortName: "三岔值守",
    playerPower: 32,
    boss: 58,
    tip: "中间偏稳，边路偏赚，真正的坑在你想两头都要的时候。",
    a: T(5),
    b: E(9),
    c: E(28),
    d: E(19),
    e: P(11),
    f: T(8),
    g: E(24),
    h: E(33),
    i: P(10),
    j: E(15),
    k: E(30),
    l: T(11)
  }),
  makeTowerLevel({
    id: 13,
    name: "第 13 关 · 偏门赌注",
    shortName: "偏门赌注",
    playerPower: 34,
    boss: 60,
    tip: "钥匙藏在角落里，偏门的价值第一次比正门更高。",
    a: K(),
    b: E(10),
    c: E(36),
    d: P(12),
    e: T(14),
    f: E(22),
    g: T(8),
    h: E(28),
    i: L(),
    j: P(14),
    k: E(40),
    l: E(18)
  }),
  makeTowerLevel({
    id: 14,
    name: "第 14 关 · 锁门双选",
    shortName: "锁门双选",
    playerPower: 36,
    boss: 62,
    tip: "有钥匙不代表可以乱开，开错那一扇门就没有下文了。",
    a: E(17),
    b: K(),
    c: P(10),
    d: E(24),
    e: T(6),
    f: T(16),
    g: E(30),
    h: E(33),
    i: P(12),
    j: E(14),
    k: E(42),
    l: L()
  }),
  makeTowerLevel({
    id: 15,
    name: "第 15 关 · 火线穿塔",
    shortName: "火线穿塔",
    playerPower: 38,
    boss: 68,
    tip: "强敌、补给和钥匙都挤在一团里，决策速度会被卡得很难受。",
    a: E(20),
    b: P(11),
    c: K(),
    d: E(27),
    e: P(13),
    f: E(25),
    g: T(15),
    h: E(38),
    i: E(30),
    j: E(16),
    k: P(15),
    l: L()
  }),
  makeTowerLevel({
    id: 16,
    name: "第 16 关 · 数值盘算",
    shortName: "数值盘算",
    playerPower: 40,
    boss: 72,
    tip: "这关要把每一层的净收益都算清楚，不能再只凭直觉点了。",
    a: E(22),
    b: K(),
    c: E(34),
    d: E(30),
    e: P(12),
    f: L(),
    g: T(9),
    h: E(41),
    i: T(15),
    j: P(18),
    k: E(18),
    l: E(44)
  }),
  makeTowerLevel({
    id: 17,
    name: "第 17 关 · 交叉高台",
    shortName: "交叉高台",
    playerPower: 42,
    boss: 78,
    tip: "开始进入真正的中后段，很多路都能走，但只有一两条能打穿。",
    a: E(10),
    b: E(24),
    c: K(),
    d: P(12),
    e: P(6),
    f: E(28),
    g: E(20),
    h: E(35),
    i: T(18),
    j: P(15),
    k: E(42),
    l: E(20)
  }),
  makeTowerLevel({
    id: 18,
    name: "第 18 关 · 连锁机关",
    shortName: "连锁机关",
    playerPower: 44,
    boss: 82,
    tip: "先吃补给再踩陷阱，或者先踩陷阱再换收益，这回顺序就是命。",
    a: E(24),
    b: P(12),
    c: T(14),
    d: E(32),
    e: T(7),
    f: E(29),
    g: P(6),
    h: E(40),
    i: E(33),
    j: E(18),
    k: P(16),
    l: E(18)
  }),
  makeTowerLevel({
    id: 19,
    name: "第 19 关 · 四层封锁",
    shortName: "四层封锁",
    playerPower: 46,
    boss: 86,
    tip: "这回是典型的塔楼封锁局，钥匙拿晚了，上面那层就彻底没戏了。",
    a: E(26),
    b: K(),
    c: P(11),
    d: E(34),
    e: T(20),
    f: E(31),
    g: T(10),
    h: E(43),
    i: L(),
    j: P(18),
    k: E(22),
    l: E(47)
  }),
  makeTowerLevel({
    id: 20,
    name: "第 20 关 · 陷阱账本",
    shortName: "陷阱账本",
    playerPower: 48,
    boss: 90,
    tip: "错一格就会亏整层，这关更像在做一张摸鱼损益表。",
    a: E(28),
    b: T(8),
    c: K(),
    d: P(12),
    e: E(36),
    f: E(34),
    g: T(20),
    h: E(46),
    i: E(38),
    j: L(),
    k: P(20),
    l: E(24)
  }),
  makeTowerLevel({
    id: 21,
    name: "第 21 关 · 总控前哨",
    shortName: "总控前哨",
    playerPower: 50,
    boss: 96,
    tip: "最后四关开始了，塔楼已经不再给你容错空间。",
    a: T(14),
    b: E(30),
    c: K(),
    d: P(14),
    e: E(16),
    f: E(37),
    g: T(12),
    h: E(49),
    i: K(),
    j: P(19),
    k: E(44),
    l: T(18)
  }),
  makeTowerLevel({
    id: 22,
    name: "第 22 关 · 双钥匙塔",
    shortName: "双钥匙塔",
    playerPower: 56,
    boss: 100,
    tip: "看见两把钥匙别高兴太早，真正值钱的是你还能带着多少战力上顶层。",
    a: E(34),
    b: T(14),
    c: P(14),
    d: E(40),
    e: K(),
    f: T(16),
    g: E(42),
    h: E(53),
    i: T(16),
    j: L(),
    k: E(22),
    l: E(48)
  }),
  makeTowerLevel({
    id: 23,
    name: "第 23 关 · Boss 预演",
    shortName: "Boss 预演",
    playerPower: 58,
    boss: 104,
    tip: "这是最终关前的模拟战，路线不只是要通，还得够快够稳。",
    a: E(36),
    b: K(),
    c: T(10),
    d: E(44),
    e: P(16),
    f: E(39),
    g: T(22),
    h: E(55),
    i: E(45),
    j: L(),
    k: P(22),
    l: E(26)
  }),
  makeTowerLevel({
    id: 24,
    name: "第 24 关 · 摸鱼之巅",
    shortName: "摸鱼之巅",
    playerPower: 60,
    boss: 108,
    tip: "最后一关不让你拼手速，只拼一路到底的判断力。上去了，就是真正的摸鱼塔顶。",
    a: K(),
    b: T(12),
    c: E(40),
    d: P(18),
    e: T(24),
    f: E(42),
    g: P(14),
    h: E(58),
    i: L(),
    j: E(48),
    k: E(30),
    l: E(54)
  })
];
