window.STICK_TOWER_LEVELS = [
  {
    id: 1,
    name: "第 1 关 · 热身教学",
    shortName: "热身教学",
    playerPower: 10,
    playerStart: 1,
    winRoom: 7,
    tip: "先吃掉低战力守卫，再补宝箱，最后去挑战 Boss。",
    rooms: [
      { id: 1, x: 1, y: 5, type: "start" },
      { id: 2, x: 1, y: 4, type: "enemy", value: 4 },
      { id: 3, x: 2, y: 4, type: "treasure", value: 6 },
      { id: 4, x: 0, y: 4, type: "enemy", value: 14 },
      { id: 5, x: 2, y: 3, type: "enemy", value: 9 },
      { id: 6, x: 1, y: 3, type: "treasure", value: 4 },
      { id: 7, x: 1, y: 2, type: "boss", value: 26 }
    ],
    links: [
      [1, 2],
      [2, 3],
      [2, 4],
      [3, 5],
      [5, 6],
      [6, 7]
    ]
  },
  {
    id: 2,
    name: "第 2 关 · 钥匙回廊",
    shortName: "钥匙回廊",
    playerPower: 12,
    playerStart: 1,
    winRoom: 8,
    tip: "钥匙不只是开门，还决定你能不能拿到后面的战力补给。",
    rooms: [
      { id: 1, x: 1, y: 5, type: "start" },
      { id: 2, x: 0, y: 4, type: "key", value: 1 },
      { id: 3, x: 1, y: 4, type: "enemy", value: 5 },
      { id: 4, x: 2, y: 4, type: "treasure", value: 6 },
      { id: 5, x: 1, y: 3, type: "lock", value: 1 },
      { id: 6, x: 0, y: 2, type: "enemy", value: 9 },
      { id: 7, x: 1, y: 2, type: "treasure", value: 5 },
      { id: 8, x: 2, y: 2, type: "boss", value: 26 }
    ],
    links: [
      [1, 2],
      [1, 3],
      [1, 4],
      [2, 3],
      [3, 5],
      [4, 5],
      [5, 6],
      [5, 7],
      [6, 7],
      [7, 8]
    ]
  },
  {
    id: 3,
    name: "第 3 关 · 陷阱试算",
    shortName: "陷阱试算",
    playerPower: 14,
    playerStart: 1,
    winRoom: 9,
    tip: "看起来最近的路，不一定是最赚的路。先拿钥匙再补刀。",
    rooms: [
      { id: 1, x: 1, y: 5, type: "start" },
      { id: 2, x: 0, y: 4, type: "enemy", value: 6 },
      { id: 3, x: 1, y: 4, type: "trap", value: 5 },
      { id: 4, x: 2, y: 4, type: "treasure", value: 8 },
      { id: 5, x: 0, y: 3, type: "enemy", value: 12 },
      { id: 6, x: 1, y: 3, type: "trap", value: 10 },
      { id: 7, x: 2, y: 3, type: "key", value: 1 },
      { id: 8, x: 1, y: 2, type: "lock", value: 1 },
      { id: 9, x: 1, y: 1, type: "boss", value: 33 }
    ],
    links: [
      [1, 2],
      [1, 3],
      [1, 4],
      [2, 5],
      [3, 5],
      [3, 6],
      [4, 7],
      [7, 8],
      [8, 5],
      [8, 9]
    ]
  },
  {
    id: 4,
    name: "第 4 关 · 分岔高塔",
    shortName: "分岔高塔",
    playerPower: 18,
    playerStart: 1,
    winRoom: 12,
    tip: "这关不能只看眼前一层，绕一圈补数值会更稳。",
    rooms: [
      { id: 1, x: 2, y: 5, type: "start" },
      { id: 2, x: 1, y: 4, type: "enemy", value: 7 },
      { id: 3, x: 2, y: 4, type: "enemy", value: 12 },
      { id: 4, x: 3, y: 4, type: "treasure", value: 5 },
      { id: 5, x: 0, y: 3, type: "key", value: 1 },
      { id: 6, x: 1, y: 3, type: "enemy", value: 16 },
      { id: 7, x: 2, y: 3, type: "trap", value: 6 },
      { id: 8, x: 3, y: 3, type: "enemy", value: 10 },
      { id: 9, x: 2, y: 2, type: "lock", value: 1 },
      { id: 10, x: 1, y: 1, type: "treasure", value: 9 },
      { id: 11, x: 3, y: 1, type: "enemy", value: 18 },
      { id: 12, x: 2, y: 0, type: "boss", value: 70 }
    ],
    links: [
      [1, 2],
      [1, 3],
      [1, 4],
      [2, 5],
      [2, 6],
      [3, 6],
      [3, 7],
      [4, 7],
      [4, 8],
      [5, 9],
      [6, 9],
      [7, 9],
      [8, 9],
      [9, 10],
      [9, 11],
      [10, 11],
      [10, 12],
      [11, 12]
    ]
  },
  {
    id: 5,
    name: "第 5 关 · 总部总测",
    shortName: "总部总测",
    playerPower: 22,
    playerStart: 1,
    winRoom: 15,
    tip: "这是综合塔。钥匙、陷阱、Boss 都在考你，别急着直冲顶层。",
    rooms: [
      { id: 1, x: 2, y: 6, type: "start" },
      { id: 2, x: 1, y: 5, type: "enemy", value: 8 },
      { id: 3, x: 2, y: 5, type: "treasure", value: 6 },
      { id: 4, x: 3, y: 5, type: "enemy", value: 15 },
      { id: 5, x: 0, y: 4, type: "key", value: 1 },
      { id: 6, x: 1, y: 4, type: "trap", value: 7 },
      { id: 7, x: 2, y: 4, type: "enemy", value: 18 },
      { id: 8, x: 3, y: 4, type: "treasure", value: 9 },
      { id: 9, x: 2, y: 3, type: "lock", value: 1 },
      { id: 10, x: 0, y: 2, type: "enemy", value: 12 },
      { id: 11, x: 1, y: 2, type: "treasure", value: 11 },
      { id: 12, x: 2, y: 2, type: "trap", value: 10 },
      { id: 13, x: 3, y: 2, type: "enemy", value: 20 },
      { id: 14, x: 2, y: 1, type: "enemy", value: 24 },
      { id: 15, x: 2, y: 0, type: "boss", value: 96 }
    ],
    links: [
      [1, 2],
      [1, 3],
      [1, 4],
      [2, 5],
      [2, 6],
      [3, 6],
      [3, 7],
      [4, 7],
      [4, 8],
      [5, 9],
      [6, 9],
      [7, 9],
      [8, 9],
      [9, 10],
      [9, 11],
      [9, 12],
      [9, 13],
      [10, 14],
      [11, 14],
      [12, 14],
      [13, 14],
      [14, 15]
    ]
  }
];
